### ISSUE TITLE
Sample json config

### ISSUE THREAD

**Issue by adireddy** [mcheshkov/haxelint#5]
Hi @mcheshkov, do you have a sample json format that I can refer to? Thanks.

**Comment by mcheshkov** [comment]
Hi @adireddy.
Sorry, I've put lint on hold, so no docs, releases or whatever.
Current format is like this

    {
        "checks":[
                {
                        "type": "IndentationCharacter"
                },
                {
                        "type": "Spacing",
                        "props": {
                                "spaceIfCondition": false
                        }
                }
        ]
    }

For possible type values refer to source, seek for `@name` meta, like [here](https://github.com/mcheshkov/haxelint/blob/master/src/haxelint/checks/ArrayInstantiationCheck.hx#L6)
Props will be treated as-is, so you should care of types manually.

**Comment by adireddy** [comment]
Thanks :+1:

**Comment by adireddy** [comment]
Hi @mcheshkov, do you mind adding me as a collaborator so that I can update the documentation and also try and fix Interface variable issue.

Thought of updating my fork but don't want to duplicate the effort.

**Comment by mcheshkov** [comment]
What kind of effort you will duplicate? I'd prefer pull request.

**Comment by adireddy** [comment]
That's fine.
